const questions = {
  firstLoad: true,
  demographicQuestions: {
    name: 'Demographic Survey',
    questionList: [
      {
        id: 1,
        label: 'Age',
        text: 'What is your Age?',
        type: 'option',
        options: [
          'Below 18',
          '18 - 24',
          '25 - 34',
          '35 - 44',
          '45 - 54',
          '55 - 64',
          'Above 65',
        ],
      },
      {
        id: 2,
        label: 'Gender Identity',
        text: 'What gender do you identify as?',
        type: 'option',
        options: [
          'Male',
          'Female',
          'Transgender',
          'Non-binary',
          'Prefer not to answer',
          'Other',
        ],
      },
      {
        id: 3,
        label: 'Marital Status',
        text: 'What is your marital status?',
        type: 'option',
        options: [
          'Married',
          'Divorced',
          'Separated',
          'Single',
          'Prefer not to say',
        ],
      },
      {
        id: 4,
        label: 'Location',
        text: 'Which region in England do you live?',
        type: 'option',
        options: [
          'South West',
          'South East',
          'Greater London',
          'East of England',
          'West Midlands',
          'East Midlands',
          'Yorkshire and Humber',
          'North West',
          'North East',
        ],
      },
      {
        id: 5,
        label: 'Ethnic Background',
        text: 'What is your ethnic background? ',
        type: 'option',
        options: [
          'White / Caucasian',
          'Asian/Asian British',
          'Black/African/Caribbean/Black British',
          'Mixed/Multiple ethnic groups',
          'Other ethnic group',
        ],
      },
      {
        id: 6,
        label: 'Education Level',
        text: 'Please select the highest level of education that you have attained?',
        type: 'option',
        options: [
          'Doctorate degree',
          'Master’s degree',
          'Bachelor’s degree',
          'Associate degree',
          'Trade/technical/vocational training',
          'High school/college graduate, diploma or equivalent',
          'Some high school',
          'Other',
          'Prefer not to say',
        ],
      },
      {
        id: 7,
        label: 'Employment Status',
        text: 'Which of the following best describes your current employment status?',
        type: 'option',
        options: [
          'Full-time employment',
          'Self-employed',
          'Part-time employment',
          'Underemployed (wage is below industry average)',
          'Full time freelancing',
          'Unemployed (looking for work)',
          'Unemployed (not looking for work)',
          'Student',
          'Inability to work',
        ],
      },
    ],

    //[
    //   { id: 1, text: 'What is your age?', type: 'text' },
    //   { id: 2, text: 'What is your gender identity?', type: 'text' },
    //   {
    //     id: 3,
    //     text: 'What is your ethnicity or race?',
    //     type: 'droplist',
    //     options: ['Red', 'Green', 'Blue'],
    //   },
    //   { id: 4, text: 'Where are you located?', type: 'text' },
    //   {
    //     id: 5,
    //     text: 'What is your highest level of education completed?',
    //     type: 'text',
    //   },
    //   {
    //     id: 6,
    //     text: 'What is your approximate household income?',
    //     type: 'text',
    //   },
    //   {
    //     id: 7,
    //     text: 'What is the highest level of education and approximate income of your parents or guardians?',
    //     type: 'text',
    //   },
    //   { id: 8, text: 'Are you currently employed?', type: 'text' },
    //   {
    //     id: 9,
    //     text: 'What is the primary language spoken at home?',
    //     type: 'text',
    //   },
    //   {
    //     id: 10,
    //     text: 'Do you have any accessibility needs we should be aware of?',
    //     type: 'text',
    //   },
    //   { id: 11, text: 'What are your interests or hobbies?', type: 'text' },
    //   {
    //     id: 12,
    //     text: 'Have you attended similar workshops or events before?',
    //     type: 'text',
    //   },
    //   {
    //     id: 13,
    //     text: 'How did you find out about our workshops?',
    //     type: 'text',
    //   },
    // ],
  },

  generalSurveyQuestions: {
    name: 'General Survey',
    questionList: [
      {
        id: 8,
        label: 'Satisfaction',
        text: 'How satisfied are you with the registration process?',
        type: 'option',
        options: ['Not Satisfied', 'Neutral', 'Satisfied'],
      },
      {
        id: 9,
        label: 'Future Topics',
        text: 'What topics would you like to see covered in future workshops?',
        type: 'text',
      },
      {
        id: 10,
        label: 'Attend Likelihood',
        text: 'On a scale of 1 to 10, how likely are you to attend our future events?',
        type: 'option',
        options: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
      },
      {
        id: 11,
        label: 'Material Understandability',
        text: 'Do you find our workshop materials easy to understand?',
        type: 'option',
        options: ['Yes', 'No'],
      },
      {
        id: 12,
        label: 'Reason Attending',
        text: 'What is the primary reason you attended this workshop?',
        type: 'text',
      },
      {
        id: 13,
        label: 'Awareness',
        text: 'How did you hear about our organization?',
        type: 'text',
      },
      {
        id: 14,
        label: 'Quality Rating',
        text: 'Rate the overall quality of the event on a scale of 1 to 5.',
        type: 'option',
        options: ['1', '2', '3', '4', '5'],
      },
      {
        id: 15,
        label: 'Improvement Suggestions',
        text: 'What suggestions do you have for improving our events?',
        type: 'text',
      },
      {
        id: 16,
        label: 'Expectations Met',
        text: 'Did the event meet your expectations? Why or why not?',
        type: 'text',
      },
      {
        id: 17,
        label: 'Recommend Likelihood',
        text: 'How likely are you to recommend our events to a friend or colleague?',
        type: 'option',
        options: ['Not Likely', 'Neutral', 'Very Likely'],
      },
      {
        id: 18,
        label: 'Interest Speaking',
        text: 'Would you be interested in participating as a speaker or presenter in future events?',
        type: 'option',
        options: ['Yes', 'No'],
      },
      {
        id: 19,
        label: 'Preferred Channels',
        text: 'What platform or channels do you prefer for receiving event updates?',
        type: 'text',
      },
    ],

    //[
    //   {
    //     id: 14,
    //     text: 'How satisfied are you with the registration process?',
    //     type: 'scale',
    //     options: ['Not Satisfied', 'Neutral', 'Satisfied'],
    //   },
    //   {
    //     id: 15,
    //     text: 'What topics would you like to see covered in future workshops?',
    //     type: 'text',
    //   },
    //   {
    //     id: 16,
    //     text: 'On a scale of 1 to 10, how likely are you to attend our future events?',
    //     type: 'scale',
    //     options: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
    //   },
    //   {
    //     id: 17,
    //     text: 'Do you find our workshop materials easy to understand?',
    //     type: 'yesno',
    //   },
    //   {
    //     id: 18,
    //     text: 'What is the primary reason you attended this workshop?',
    //     type: 'text',
    //   },
    //   {
    //     id: 19,
    //     text: 'How did you hear about our organization?',
    //     type: 'text',
    //   },
    //   {
    //     id: 20,
    //     text: 'Rate the overall quality of the event on a scale of 1 to 5.',
    //     type: 'scale',
    //     options: ['1', '2', '3', '4', '5'],
    //   },
    //   {
    //     id: 21,
    //     text: 'What suggestions do you have for improving our events?',
    //     type: 'text',
    //   },
    //   {
    //     id: 22,
    //     text: 'Did the event meet your expectations? Why or why not?',
    //     type: 'text',
    //   },
    //   {
    //     id: 23,
    //     text: 'How likely are you to recommend our events to a friend or colleague?',
    //     type: 'scale',
    //     options: ['Not Likely', 'Neutral', 'Very Likely'],
    //   },
    //   {
    //     id: 24,
    //     text: 'Would you be interested in participating as a speaker or presenter in future events?',
    //     type: 'yesno',
    //   },
    //   {
    //     id: 25,
    //     text: 'What platform or channels do you prefer for receiving event updates?',
    //     type: 'text',
    //   },
    //   // Add more general survey questions as needed
    // ],
  },
};

export { questions };
